### PR TITLE
Haskell-CI on GitHub Actions for GHC 7.0 - 9.4

### PR DESCRIPTION
**Pull request by andreasabel**
Successful run at: https://github.com/andreasabel/hsc2hs/actions/runs/2401482742

### CODE REVIEW

**Comment by andreasabel** [comment]
Ping @bgamari @ggreif.

**Review by ggreif — COMMENTED** [review]
There doesn't seem to be a GH action running at all. Maybe you have to flip one more switch.

**Comment by andreasabel** [comment]
> There doesn't seem to be a GH action running at all. Maybe you have to flip one more switch.

@ggreif
It will after you merged, as this is the first workflow.  This is why I point to the "successful run" on my fork.
If it doesn't run after merging then you have deactivated actions and have to turn them on.  Please not that I do not have the rights to make any settings on this repo.

**Comment by ggreif** [comment]
Okay, I don't know how I got the bit-of-privilege™, but I'll just merge this now!

**Review by ggreif — APPROVED** [review]
Let's give this a try!

**Comment by ggreif** [comment]
Okay, the action just kicked in gear!

**Pull request merged**
