### PR TITLE
spec: add more assembly examples surrently broken for GHC

### PR DESCRIPTION
**Pull request by trofi**
These are tests to illustrate GHC cross-compilation failures:
    https://ghc.haskell.org/trac/ghc/ticket/14889
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>

### CODE REVIEW

**Comment by angerman** [comment]
@trofi thank you so much for these!

**Comment by hvr** [comment]
@trofi could you please rebase this against `master`? That way we'd see the testsuite output in via CI

**Comment by trofi** [comment]
Rebased.

**Pull request merged**
